docs: textField.md 추가
flutter-seoul/tutorial pull request #5
Opened 2022-10-31 16:12 UTC by nain93

# Why
자주 쓰이는 textField 문서화를 위한 textField.md 추가
# How
몇가지 종류의 textField 공통 코드를 작성하고 gif, png로 시각화

2022-11-01 15:35 UTC, hyochan requested changes
**Note:** 를 설명에서 빼줘도 무방할 것 같아요.

2022-11-01 15:35 UTC, hyochan commented on flutter/textField.md
> +> **Note:** **TextFormField** is This is a convenience widget that wraps a TextField widget in a FormField.
`**Note:** **TextFormField** is` 여기까지 삭제하면 좋을 것 같아요.

2022-11-03 03:11 UTC, hyochan requested changes

2022-11-03 03:11 UTC, hyochan commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).
expo 내용이 있는데 이건 빼주시는게 좋겠네요

2022-11-03 03:11 UTC, hyochan commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg: updated a module plugin).
플러터 관련된 사항이 있으면 넣어주세요.

2022-11-03 03:11 UTC, hyochan commented on flutter/tabBar.md
> +> **Note:** Default BottomNavigationBar.
`Note` 앞에 빼주시고 `BottomNavigationBar`에 대해서 설명을 적어주시면 좋겠습니다. `BottomNavigationBar`가 무엇인지?

그리고 한글로 적어주세요.

2022-11-03 03:11 UTC, hyochan commented on flutter/tabBar.md
> +
마찬가지입니다.

2022-11-03 03:11 UTC, hyochan commented on flutter/tabBar.md
> +> **Note:** If you use **Radius BottomNavigationBar**, it is natural to set the extendBody option to true.
이게 어떤 내용인지 이해가 잘 안되는데 조금 더 명확하게 작성해주실 수 있으면 좋겠습니다.

2022-11-03 03:11 UTC, hyochan commented on flutter/textField.md
> +> **Note:** You can add other prefix or suffix.
다른데서는 `prefix`와 `suffix`를 사용할 수 없는 것인지요?

2022-11-03 15:54 UTC, nain93 commented
설명 전부 한글로 변경하고 부가설명 및 도움이 될 수 있는 링크들 추가했습니다
Radius BottomNavigationBar부분은 이미지 추가하여 좀 더 이해하기 쉽게 수정했습니다

PR템플릿도 한글로 수정하고 약간의 추가 설명을 넣었습니다

2022-11-04 03:21 UTC, hyochan approved these changes
수고하셨습니다. 파일명만 다트에서 선호하는 `lower_snake_case`로 변경하였습니다.

2022-11-04 03:21 UTC, merged

2022-11-04 03:22 UTC, hyochan commented
> # Why
> 자주 쓰이는 textField 문서화를 위한 textField.md 추가
> 
> # How
> 몇가지 종류의 textField 공통 코드를 작성하고 gif, png로 시각화

"자주 쓰이는", "몇가지 종류" 등의 추상적 용어를 쓰지 않으려고 노력해주시면 좋을 것 같습니다.