popup.md 문서 추가
flutter-seoul/tutorial pull request #8
Opened 2022-11-04 09:54 UTC by nain93

## PR 이유

popup 관련 위젯을 정리한 popup.md 문서를 추가합니다

## 변경 내용

popup.md 에 Button Popup, Toast Popup, Bottom Sheet Popup 코드 및, 설명을 추가합니다

2022-11-08 10:01 UTC, hyochan requested changes

2022-11-08 10:01 UTC, hyochan commented on flutter/view.md
> +또한, `addAutomaticKeepAlives`, `cacheExtent` 속성으로 화면 밖 리스트가 유지되지 않게 해줄 수 있습니다.
`addAutomaticKeepAlives`와 `cacheExtent`가 무언지 설명 해주시면 좋을 것 같습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/buttons.md
> +[dialogs][dialogLink] or [cards][cardLink]같은 이미 높은 위젯 위에 사용하면 안됩니다.
"이미 높은 위젯"이란 말이 모호하여 "상위 위젯"등 다른 표현을 써주면 좋겠습니다. 더불어 사용하면 왜 안되는지 설명이 필요해보입니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/buttons.md
> +[ToggleButtons][ToggleButtonsLink]은 여러개의 옵션을 선택할 수 있는 버튼입니다. `isSelected` 속성에 bool타입으로 선택 됐는지 여부를 체크할 수 있으며 `isSelected`에 제공된 배열의 길이와 `children` 속성 길이는 같아야 합니다.
체크할 수 있으며 => "체크할 수 있습니다"로 바꿔주시고 아래 는 중요로 빼서 
`* `로 시작하는 문장을 만들면 좋을 것 같습니다. 설명보다는 주의를 요하는 문장으로 구분을 하면 좋을 것 같다는 의미입니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/buttons.md
> +화면당 최대 하나의 버튼을 사용하고 "만들기", "공유" 또는 "탐색"과 같은 긍정적인 작업에 사용해야 합니다.
"만들기", "공유" 또는 "탐색"이 어떠한 긍정적인 작업인지 모호하게 느껴집니다. 부정적인 작업중 하면 안되는 것도 추가하면 이해하는데 도움이 될 것 같습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/buttons.md
> +[PopupMenuButton][PopupMenuButtonLink]은 여러개의 옵션을 선택 할 수 있는 버튼이고 열고 닫을 수 있습니다
`.`가 빠졌습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +바깥영역을 클릭하거나 `onPressed`에 `Navigator.of(context).pop()`를 추가해서 팝업을 끌 수 있습니다
마침표가 빠졌습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +`title`항목과 `content`항목으로 나누어서 구성하고 `actions` 옵션에 버튼을 추가할 수 있습니다
마침표가 빠졌습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +바깥영역을 클릭하거나 `onPressed`에 `Navigator.of(context).pop()`를 추가해서 팝업을 끌 수 있습니다
바깥영역 => `바깥 영역`

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +[AnimationController][AnimationControllerLink]를 사용해 애니메이션을 적용하고 `initState()`에서 실행시키며 `dispose()`로 제거해줍니다 (controller 할당후 dispose()로 삭제해야합니다)
마침표가 빠졌습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +[SlideTransition][SlideTransitionLink]을 활용한 아래에서 올라오는 **ToastPopup**입니다
마침표가 빠졌습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +[SnackBar][SnackBarLink]로도 Toast popup을 구현할 수 있습니다. [ScaffoldMessenger][ScaffoldMessengerLink]를 사용하여 snackBar를 띄웁니다. `ScaffoldMessenger`는 모든 [Scaffold][ScaffoldLink] 상위에서 작동하여 토스트가 나아도록 해줍니다.
`나아도록` => `나오도록`

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +[SnackBar][SnackBarLink]로도 Toast popup을 구현할 수 있습니다. [ScaffoldMessenger][ScaffoldMessengerLink]를 사용하여 snackBar를 띄웁니다. `ScaffoldMessenger`는 모든 [Scaffold][ScaffoldLink] 상위에서 작동하여 토스트가 나아도록 해줍니다.
`작동하여` => `작동하며`

2022-11-08 10:01 UTC, hyochan commented on flutter/popup.md
> +SnackBar는 `action` 속성에 `SnackBarAction`위젯의 `onPressed` 속성으로 버튼을 추가할 수 있습니다.
`action 속성에 snackbaraction 위젯의 onPress 속성으로 버튼을 추가`한다는 말이 어떤 건지 좀더 명확하면 좋겠습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/tab_bars.md
> +상단탭 클릭으로 화면 이동을 할 수 있는 **DefaultTabBar**입니다 또한 화면내에서 좌우 스와이프로도 화면을 이동 할 수 있습니다.(`TabBarView`의 `physics` 옵션을 활용해 스와이프를 막을수도 있습니다)
`(`TabBarView`의 `physics` 옵션을 활용해 스와이프를 막을수도 있습니다)` 위 만장에서 괄호를 걷어내도 좋을 것 같습니다. 마침표도 찍어주시고요.

2022-11-08 10:01 UTC, hyochan commented on flutter/tab_bars.md
> +PreferredSize옵션을 사용해 Tab의 높이를 조정 할 수도 있고, 선택된 탭과 안된 탭에 따로 스타일을 적용할 수도 있습니다.
`PreferredSize옵션을` => `PreferredSize 옵션을`

2022-11-08 10:01 UTC, hyochan commented on flutter/tab_bars.md
> +**BottomNavigationBar**에 [ClipRRect][ClipRRectlink] 위젯을 활용해 좌우 radius 곡선을 준 navigation입니다. 이 경우 `Scaffold`에 `extendBody: true`을 주어야 자연스러운 ui를 구성할 수 있습니다.
`extendBody: true`을 => 를이 자연스럽게 읽히는 것 같습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/tab_bars.md
> +[SliverAppBar][SliverAppBarlink] 위젯을 활용하여 스크롤 가능한 `TabBar`입니다 `pinned: true` 옵션으로 상단에 TabBar가 충돌했을때 고정됩니다. [FlexibleSpaceBar][FlexibleSpaceBarlink]로 상단에 표시될 화면을 제공하고 [SliverPersistentHeader][SliverPe
마침표 찍어주세요.

2022-11-08 10:01 UTC, hyochan commented on flutter/tab_bars.md
>  delegate 옵션 SliverPersistentHeaderDelegate에 TabBar를 내려주는 방식으로 구성됩니다.
TabBar를 내려주는 방식이 어떤건지 궁금합니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/text_fields.md
> +`keyboardType`으로 키보드형태를 변경할 수 있고 `hintText` 옵션으로 어떤 입력값을 넣어야하는지 알려 줄 수 있습니다.
`hintText`는 일반적인 `TextField`에서 `placeholder`라고만 명시해줘도 좋을 것 같습니다.

2022-11-08 10:01 UTC, hyochan commented on flutter/text_fields.md
> +**TextField**에서 옵션만 추가된 형태로 `prefix`, `suffix` 옵션을 추가해서 입력값이외에 `TextField`안에 widget을 추가할 수 있습니다.
입력값 이외에

2022-11-08 10:01 UTC, hyochan commented on flutter/text_fields.md
> +- 참고: `prefixText` 또는 `suffixText`의 경우 `TextField`에서 포커스 아웃 됐을때 사라지므로 포커스 아웃됐을때도 유지하고 싶다면 `prefixIcon` 또는 `suffixIcon`, child Text를 넣어줘야 합니다.
아웃 됐을때 => 아웃됐을 때
아웃됐을때도 => 아웃됐을 때도

2022-11-08 10:01 UTC, hyochan commented on flutter/view.md
> +`primary` 속성이 true이면 실제로 스크롤하기에 충분한 콘텐츠가 없는 경우에도 스크롤 뷰를 스크롤할 수 있습니다.
스크롤하기에 => 스크롤 하기에
스크롤할 => 스크롤 할

2022-11-09 04:31 UTC, hyochan requested changes

2022-11-09 04:31 UTC, hyochan commented on flutter/buttons.md
여전히 여기 말이 모호하게 들리는데요. 관련하여 예시나 첨언을 해줄 수 있으면 좋겠습니다.

2022-11-09 04:31 UTC, hyochan commented on flutter/tab_bars.md
> +[SliverAppBar][SliverAppBarlink] 위젯을 활용하여 스크롤 가능한 `TabBar`입니다 `pinned: true` 옵션으로 상단에 TabBar가 충돌했을때 고정됩니다. [FlexibleSpaceBar][FlexibleSpaceBarlink]로 상단에 표시될 화면을 제공하고 [SliverPersistentHeader][SliverPe
여기 반영이 안되었습니다.

2022-11-09 04:45 UTC, hyochan commented
@nain93 
<img width="389" alt="Screenshot 2022-11-09 at 1 44 07 PM" src="https://user-images.githubusercontent.com/27461460/200740662-ea96c773-aece-4cdf-8f2c-bdccf448a232.png">

"..합니다"는 이유가 아닙니다. 변경내용에 포함시켜주시면 좋을 것 같습니다. 그리고 마침표도 찍어주시고 각각 action에 대해서 보충 설명할 수 있는 부분도 있으면 좋겠습니다.

2022-11-09 05:00 UTC, nain93 commented on flutter/buttons.md
> +[dialogs][dialogLink] or [cards][cardLink]같은 이미 높은 위젯 위에 사용하면 안됩니다.
공식문서에 나온의미를 보면 위젯트리의 상위 개념이아니라 높이가 높다, 화면에서 앞으로 나와있다라는 뜻으로 보여서
'이미 높이가 높기 때문에 사용을 피하는것을 권장합니다.' 라고 수정했습니다

2022-11-09 05:01 UTC, nain93 commented on flutter/buttons.md
공식문서에 나온의미를 보면 위젯트리의 상위 개념이아니라 높이가 높다, 화면에서 앞으로 나와있다라는 뜻으로 보여서
'이미 높이가 높기 때문에 사용을 피하는것을 권장합니다.' 라고 수정했습니다

2022-11-09 05:47 UTC, nain93 commented on flutter/buttons.md
https://api.flutter.dev/flutter/material/ElevatedButton-class.html
flutter 공식문서에서 사용을 피하라고 되어있고 특정 이유는 안나와있습니다
elevated 버튼이랑 card 위젯이 둘다 높이가 높기 때문에 같이 사용했을경우 UI상 구분이 어려울 수 있기 때문에 피하라는 뜻으로 보입니다

2022-11-10 05:28 UTC, hyochan approved these changes

2022-11-10 06:27 UTC, merged